version: "3.9"
services:
  bot:
    image: ghcr.io/marnixah/xi-jinping-bot:master
    environment: 
      TOKEN: ""OTE5MDkzMzMxODUyNjYwNzM3.YbQyXg.-7xRLu1aOQydF5nS1eVFoc5WDX8""
      BACKEND_HOST: backend:8080
      MONGO_URI: mongodb://ccp:xiIsBest@database:27017
    links: 
      - "database"
      - "backend"
  backend:
    image: ghcr.io/marnixah/xi-jinping-backend:master
    environment:
      MONGO_URI: mongodb://ccp:xiIsBest@database:27017
      PORT: "8080"
    links:
      - "database"
  database:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ccp
      MONGO_INITDB_ROOT_PASSWORD: xiIsBest
