name: Backend Docker Image CI

on:
  push:
    branches: ["refactor/monorepo"]
  pull_request:
    branches: ["refactor/monorepo"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file packages/backend/Dockerfile --tag ghcr.io/sophiah67/xi-jinping-bot:backend
      - name: Push the Docker image
        run: docker push ghcr.io/sophiah67/xi-jinping-bot:backend
